DBScan: DBScan.cpp Data.cpp Util.cpp 
	g++ DBScan.cpp Data.cpp Util.cpp -march=native -O3 -Wall -Wextra -fopenmp -o DBScan

PSO: PSO.cpp Util.cpp
	g++ PSO.cpp Util.cpp -march=native -O3 -Wall -Wextra -fopenmp -o PSO

clean:
	rm DBScan PSO
